2019-03-30 08:44:43,771 INFO: Microblog startup [in C:\Users\Solomon\Documents\Bison Hacks\startupHU\app\__init__.py:43]
2019-03-30 08:44:48,702 ERROR: Exception on / [GET] [in c:\users\solomon\documents\hackathon\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Solomon\Documents\Bison Hacks\startupHU\app\routes.py", line 12, in before_request
    if current_user.is_authenticated:
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\werkzeug\local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\werkzeug\local.py", line 307, in _get_current_object
    return self.__local()
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\flask_login\utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\flask_login\utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\flask_login\login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\flask_login\login_manager.py", line 321, in reload_user
    user = self.user_callback(user_id)
  File "C:\Users\Solomon\Documents\Bison Hacks\startupHU\app\models.py", line 65, in load_user
    return User.query.get(int(id))
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\orm\query.py", line 959, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\orm\query.py", line 1069, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\orm\loading.py", line 282, in load_on_pk_identity
    return q.one()
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3275, in one
    ret = self.one_or_none()
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3244, in one_or_none
    ret = list(self)
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\util\compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\util\compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\solomon\documents\hackathon\venv\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen 
FROM user 
WHERE user.id = ?]
[parameters: (1,)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-03-30 08:45:27,781 INFO: Microblog startup [in C:\Users\Solomon\Documents\Bison Hacks\startupHU\app\__init__.py:43]
2019-03-30 08:45:31,404 INFO: Microblog startup [in C:\Users\Solomon\Documents\Bison Hacks\startupHU\app\__init__.py:43]
2019-03-30 08:45:38,545 INFO: Microblog startup [in C:\Users\Solomon\Documents\Bison Hacks\startupHU\app\__init__.py:43]
2019-03-30 08:45:44,504 INFO: Microblog startup [in C:\Users\Solomon\Documents\Bison Hacks\startupHU\app\__init__.py:43]
2019-03-30 08:58:24,376 INFO: Microblog startup [in C:\Users\Solomon\Documents\Bison Hacks\startupHU\app\__init__.py:77]
